import 'package:flutter/material.dart';
import 'app_colors.dart';

abstract final class AppTheme {
  static ThemeData get dark {
      return ThemeData(
            useMaterial3: true,
                  brightness: Brightness.dark,

                        scaffoldBackgroundColor: AppColors.background,

                              colorScheme: const ColorScheme.dark(
                                      primary: AppColors.primary,
                                              secondary: AppColors.secondary,
                                                      surface: AppColors.surface,
                                                              error: AppColors.error,
                                                                    ),

                                                                          appBarTheme: const AppBarTheme(
                                                                                  backgroundColor: AppColors.background,
                                                                                          foregroundColor: AppColors.textPrimary,
                                                                                                  elevation: 0,
                                                                                                          centerTitle: false,
                                                                                                                ),

                                                                                                                      cardTheme: CardThemeData(
                                                                                                                              color: AppColors.surface,
                                                                                                                                      elevation: 0,
                                                                                                                                              margin: EdgeInsets.zero,
                                                                                                                                                      shape: RoundedRectangleBorder(
                                                                                                                                                                borderRadius: BorderRadius.circular(18),
                                                                                                                                                                          side: const BorderSide(
                                                                                                                                                                                      color: AppColors.border,
                                                                                                                                                                                                  width: 1,
                                                                                                                                                                                                            ),
                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                          ),

                                                                                                                                                                                                                                inputDecorationTheme: InputDecorationTheme(
                                                                                                                                                                                                                                        filled: true,
                                                                                                                                                                                                                                                fillColor: AppColors.surfaceElevated,
                                                                                                                                                                                                                                                        hintStyle: const TextStyle(
                                                                                                                                                                                                                                                                  color: AppColors.textMuted,
                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                  labelStyle: const TextStyle(
                                                                                                                                                                                                                                                                                            color: AppColors.textSecondary,
                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                            contentPadding: const EdgeInsets.symmetric(
                                                                                                                                                                                                                                                                                                                      horizontal: 18,
                                                                                                                                                                                                                                                                                                                                vertical: 16,
                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                border: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                          borderRadius: BorderRadius.circular(16),
                                                                                                                                                                                                                                                                                                                                                                    borderSide: const BorderSide(
                                                                                                                                                                                                                                                                                                                                                                                color: AppColors.border,
                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                          enabledBorder: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: BorderRadius.circular(16),
                                                                                                                                                                                                                                                                                                                                                                                                                              borderSide: const BorderSide(
                                                                                                                                                                                                                                                                                                                                                                                                                                          color: AppColors.border,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    focusedBorder: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: BorderRadius.circular(16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderSide: const BorderSide(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: AppColors.primary,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                width: 1.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              elevatedButtonTheme: ElevatedButtonThemeData(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style: ElevatedButton.styleFrom(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: AppColors.primary,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          foregroundColor: Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elevation: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              minimumSize: const Size(double.infinity, 52),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        shape: RoundedRectangleBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: BorderRadius.circular(16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  textButtonTheme: TextButtonThemeData(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style: TextButton.styleFrom(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    foregroundColor: AppColors.secondary,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dividerTheme: const DividerThemeData(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: AppColors.border,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        thickness: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                space: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            navigationBarTheme: NavigationBarThemeData(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    backgroundColor: AppColors.surface,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elevation: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    indicatorColor: AppColors.primary.withValues(alpha: 0.18),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            labelTextStyle: const WidgetStatePropertyAll(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontWeight: FontWeight.w600,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }